export const movies = [
    {
      id: 1,
      category: "Acción",
      title: "John Wick",
      description: "Un exasesino busca venganza después de que le roben todo.",
      image: "https://cloudfront-us-east-1.images.arcpublishing.com/infobae/7MT227FDURHHHEQPFVJZEMWBX4.jpeg",
      trailerLink: "https://www.youtube.com/watch?v=RllJtOw0USI",
      rating: 4.5,
    },
    {
      id: 2,
      category: "Drama",
      title: "The Shawshank Redemption",
      description: "La historia de amistad y redención en una prisión.",
      image: "https://jbhelm29.files.wordpress.com/2015/06/the-shawshank-redemption-5223c8231b88e.jpg?w=842",
      trailerLink: "https://www.youtube.com/watch?v=6hB3S9bIaco",
      rating: 4.5,
    },
    {
      id: 3,
      category: "Comedia",
      title: "The Hangover",
      description: "Una desenfrenada despedida de soltero en Las Vegas.",
      image: "https://m.media-amazon.com/images/M/MV5BNGQwZjg5YmYtY2VkNC00NzliLTljYTctNzI5NmU3MjE2ODQzXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg",
      trailerLink: "https://www.youtube.com/watch?v=tcdUhdOlz9M",
      rating: 4.5,
    },
    {
      id: 4,
      category: "Aventura",
      title: "Indiana Jones and the Raiders of the Lost Ark",
      description: "El arqueólogo Indiana Jones busca un poderoso artefacto.",
      image: "https://www.kennedy-center.org/globalassets/whats-on/millennium-stage/2023/05.-may/film_raidersofthelostark_web.jpg?width=1600&quality=70",
      trailerLink: "https://www.youtube.com/watch?v=gz4crpFaW4M",
      rating: 4.5,
    },
    {
      id: 5,
      category: "Fantasía",
      title: "The Lord of the Rings: The Fellowship of the Ring",
      description: "Un grupo de personajes se embarca en una peligrosa misión.",
      image: "https://m.media-amazon.com/images/I/A1abi3dnL9L._RI_.jpg",
      trailerLink: "https://www.youtube.com/watch?v=V75dMMIW2B4",
    },
    {
      id: 6,
      category: "Romance",
      title: "The Notebook",
      description: "Un amor inolvidable a lo largo de los años.",
      image: "https://images.saymedia-content.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:eco%2Cw_1200/MTc0NDgzMTA0MzgyMDY4MzU4/facts-about-the-notebook.jpg",
      trailerLink: "https://www.youtube.com/watch?v=FC6biTjEyZw",
      rating: 4.5,
    },
    {
      id: 7,
      category: "Ciencia ficción",
      title: "Inception",
      description: "Un ladrón se adentra en los sueños de las personas.",
      image: "https://m.media-amazon.com/images/M/MV5BMjExMjkwNTQ0Nl5BMl5BanBnXkFtZTcwNTY0OTk1Mw@@._V1_.jpg",
      trailerLink: "https://www.youtube.com/watch?v=8hP9D6kZseM",
      rating: 4.5,
    },
    {
      id: 8,
      category: "Suspenso",
      title: "Gone Girl",
      description: "Un esposo busca a su esposa desaparecida.",
      image: "https://pbs.twimg.com/media/FY2ljJ_VQAAoyls.jpg:large",
      trailerLink: "https://www.youtube.com/watch?v=Ym3LB0lOJ0o",
    },
    {
      id: 9,
      category: "Animación",
      title: "Toy Story",
      description: "Los juguetes cobran vida cuando los humanos no están.",
      image: "https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_FMjpg_UX1000_.jpg",
      trailerLink: "https://www.youtube.com/watch?v=KYz2wyBy3kc",
      rating: 4.5,
    },
    {
        id: 10,
        category: "Acción",
        title: "Avengers: Endgame",
        description: "La culminación de 22 películas interconectadas.",
        image: "https://www.metroecuador.com.ec/resizer/_soVRejvssbS-JpifldHz0rqm6c=/800x0/filters:format(jpg):quality(70)/cloudfront-us-east-1.images.arcpublishing.com/metroworldnews/IMJDRFG5B5FEHNB7AHXWHUCCMQ.jpg",
        trailerLink: "https://www.youtube.com/watch?v=TcMBFSGVi1c",
        rating: 4.5,
      },
      {
        id: 11,
        category: "Comedia",
        title: "Deadpool",
        description: "Un mercenario bocazas con habilidades regenerativas.",
        image: "https://es.web.img3.acsta.net/pictures/15/12/04/10/48/099822.jpg",
        trailerLink: "https://www.youtube.com/watch?v=ONHBaC-pfsk",
        rating: 4.5,
      },

{
    id: 12,
    category: "Comedia",
    title: "Deadpool 2",
    description: "Un mercenario bocazas con habilidades regenerativas.",
    image: "https://m.media-amazon.com/images/M/MV5BMDkzNmRhNTMtZDI4NC00Zjg1LTgxM2QtMjYxZDQ3OWJlMDRlXkEyXkFqcGdeQXVyNTU5MjkzMTU@._V1_FMjpg_UX1000_.jpg",
    trailerLink: "https://www.youtube.com/watch?v=ONHBaC-pfsk",
    rating: 4.5,
  },
]